In [70]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules, fpmax

In [15]:
# https://en.wikipedia.org/wiki/Comparison_of_electoral_systems#Compliance_of_selected_single-winner_methods
df = pd.read_csv("./voting_table_wikipedia.txt", sep='\t')
display(df.columns)
df

Index(['Majority winner ', 'Majority loser ', 'Mutual majority ',
       'Condorcet winner[Tn 1] ', 'Condorcet loser ', 'Smith[Tn 1] ',
       'Smith-IIA[Tn 1] ', 'IIA/LIIA[Tn 1] ', 'Clone­proof ', 'Mono­tone ',
       'Consistency ', 'Partici­pation ', 'Reversal symmetry ',
       'Homo­geneity ', 'Later-no-harm[Tn 1] ', 'Later-no-help[Tn 1] ',
       'No favorite betrayal[Tn 1] ', 'Ballot type'],
      dtype='str')

,Majority winner,Majority loser,Mutual majority,Condorcet winner[Tn 1],Condorcet loser,Smith[Tn 1],Smith-IIA[Tn 1],IIA/LIIA[Tn 1],Clone­proof,Mono­tone,Consistency,Partici­pation,Reversal symmetry,Homo­geneity,Later-no-harm[Tn 1],Later-no-help[Tn 1],No favorite betrayal[Tn 1],Ballot type
Plurality,Yes,No,No,No,No,No,No,No,No,Yes,Yes,Yes,No,Yes,Yes,Yes,No,Single mark
Anti-plurality,No,Yes,No,No,No,No,No,No,No,Yes,Yes,Yes,No,Yes,No,No,Yes,Single mark
Two round system,Yes,Yes,No,No,Yes,No,No,No,No,No,No,No,NaN,Yes,Yes,Yes,No,Single mark
Instant-runoff,Yes,Yes,Yes,No,Yes,No,No,No,Yes,No,No,No,No,Yes,Yes,Yes,No,Ran­king
Coombs,Yes,Yes,Yes,No,Yes,No,No,No,No,No,No,No,NaN,Yes,No,No,Yes,Ran­king
Nanson,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,Yes,NaN,No,No,No,Ran­king
Baldwin,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,NaN,No,No,No,Ran­king
Tideman alternative,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,No,No,NaN,No,No,No,Ran­king
Minimax,Yes,No,No,Yes[Tn 2],No,No,No,No,No,Yes,No,No,No,NaN,No[Tn 2],No,No,Ran­king
Copeland,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,Yes,No,No,NaN,NaN,No,No,No,Ran­king
Black,Yes,Yes,No,Yes,Yes,No,No,No,No,Yes,No,No,Yes,Yes,No,No,No,Ran­king
Kemeny,Yes,Yes,Yes,Yes,Yes,Yes,Yes,LIIA Only,No,Yes,No,No,Yes,Yes,No,No,No,Ran­king
Ranked pairs,Yes,Yes,Yes,Yes,Yes,Yes,Yes,LIIA Only,Yes,Yes,No,No[Tn 3],Yes,Yes,No,No,No,Ran­king
Schulze,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,No,No[Tn 3],Yes,Yes,No,No,No,Ran­king
Borda,No,Yes,No,No,Yes,No,No,No,No,Yes,Yes,Yes,Yes,Yes,No,Yes,No,Ran­king
Bucklin,Yes,Yes,Yes,No,No,No,No,No,No,Yes,No,No,No,Yes,No,Yes,No,Ran­king
Approval,Yes,No,No,No,No,No,Yes,Yes[Tn 4],Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Appr­ovals
Majority Judgement,No,No[Tn 5],No[Tn 6],No,No,No,Yes,Yes[Tn 4],Yes,Yes,No,No[Tn 3],NaN,Yes,No,Yes,Yes,Scores
Score,No,No,No,No,No,No,Yes,Yes[Tn 4],Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Scores
STAR,No,Yes,No,No,Yes,No,No,No,No,Yes,No,No,No,NaN,No,No,No,Scores
Quadratic,No,No,No,No,No,No,No,No,No,Yes,NaN,Yes,NaN,NaN,N/A,N/A,No,Credits
Random ballot[Tn 7],No,No,No,No,No,No,Yes,Yes,Yes,Yes,NaN,Yes,NaN,Yes,Yes,Yes,Yes,Single mark
Sortition[Tn 8],No,No,No,No,No,No,Yes,Yes,No,Yes,NaN,Yes,NaN,N/A,Yes,Yes,Yes,None

In [16]:
df.columns = df.columns.str.replace(r'\[.*?\]', '', regex=True).str.strip()
for col in df.columns:
    if col != 'Ballot type':
        df[col] = df[col].fillna('Yes').replace('', 'Yes').replace(r'LIIA Only.*', 'Yes', regex=True).replace(r'N/A.*', 'Yes', regex=True).replace(r'Yes.*', 'Yes', regex=True)
        df[col] = df[col].replace(r'No.*', 'No', regex=True)
        df[col] = (df[col] == 'Yes').astype(int)
display(df.columns)
df

Index(['Majority winner', 'Majority loser', 'Mutual majority',
       'Condorcet winner', 'Condorcet loser', 'Smith', 'Smith-IIA', 'IIA/LIIA',
       'Clone­proof', 'Mono­tone', 'Consistency', 'Partici­pation',
       'Reversal symmetry', 'Homo­geneity', 'Later-no-harm', 'Later-no-help',
       'No favorite betrayal', 'Ballot type'],
      dtype='str')

,Majority winner,Majority loser,Mutual majority,Condorcet winner,Condorcet loser,Smith,Smith-IIA,IIA/LIIA,Clone­proof,Mono­tone,Consistency,Partici­pation,Reversal symmetry,Homo­geneity,Later-no-harm,Later-no-help,No favorite betrayal,Ballot type
Plurality,1,0,0,0,0,0,0,0,0,1,1,1,0,1,1,1,0,Single mark
Anti-plurality,0,1,0,0,0,0,0,0,0,1,1,1,0,1,0,0,1,Single mark
Two round system,1,1,0,0,1,0,0,0,0,0,0,0,1,1,1,1,0,Single mark
Instant-runoff,1,1,1,0,1,0,0,0,1,0,0,0,0,1,1,1,0,Ran­king
Coombs,1,1,1,0,1,0,0,0,0,0,0,0,1,1,0,0,1,Ran­king
Nanson,1,1,1,1,1,1,0,0,0,0,0,0,1,1,0,0,0,Ran­king
Baldwin,1,1,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,Ran­king
Tideman alternative,1,1,1,1,1,1,1,0,1,0,0,0,0,1,0,0,0,Ran­king
Minimax,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,Ran­king
Copeland,1,1,1,1,1,1,1,0,0,1,0,0,1,1,0,0,0,Ran­king
Black,1,1,0,1,1,0,0,0,0,1,0,0,1,1,0,0,0,Ran­king
Kemeny,1,1,1,1,1,1,1,1,0,1,0,0,1,1,0,0,0,Ran­king
Ranked pairs,1,1,1,1,1,1,1,1,1,1,0,0,1,1,0,0,0,Ran­king
Schulze,1,1,1,1,1,1,1,0,1,1,0,0,1,1,0,0,0,Ran­king
Borda,0,1,0,0,1,0,0,0,0,1,1,1,1,1,0,1,0,Ran­king
Bucklin,1,1,1,0,0,0,0,0,0,1,0,0,0,1,0,1,0,Ran­king
Approval,1,0,0,0,0,0,1,1,1,1,1,1,1,1,0,1,1,Appr­ovals
Majority Judgement,0,0,0,0,0,0,1,1,1,1,0,0,1,1,0,1,1,Scores
Score,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,1,1,Scores
STAR,0,1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,Scores
Quadratic,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,0,Credits
Random ballot[Tn 7],0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,Single mark
Sortition[Tn 8],0,0,0,0,0,0,1,1,0,1,1,1,1,1,1,1,1,None

In [17]:
df.eq(1).sum(axis=1)

Plurality                7
Anti-plurality           6
Two round system         7
Instant-runoff           8
Coombs                   7
Nanson                   8
Baldwin                  7
Tideman alternative      9
Minimax                  4
Copeland                10
Black                    7
Kemeny                  11
Ranked pairs            12
Schulze                 11
Borda                    8
Bucklin                  6
Approval                11
Majority Judgement       8
Score                   10
STAR                     4
Quadratic                7
Random ballot[Tn 7]     11
Sortition[Tn 8]         10
dtype: int64

In [ ]:
df.drop(['Ballot type'], axis=1)

,Majority winner,Majority loser,Mutual majority,Condorcet winner,Condorcet loser,Smith,Smith-IIA,IIA/LIIA,Clone­proof,Mono­tone,Consistency,Partici­pation,Reversal symmetry,Homo­geneity,Later-no-harm,Later-no-help,No favorite betrayal
Plurality,1,0,0,0,0,0,0,0,0,1,1,1,0,1,1,1,0
Anti-plurality,0,1,0,0,0,0,0,0,0,1,1,1,0,1,0,0,1
Two round system,1,1,0,0,1,0,0,0,0,0,0,0,1,1,1,1,0
Instant-runoff,1,1,1,0,1,0,0,0,1,0,0,0,0,1,1,1,0
Coombs,1,1,1,0,1,0,0,0,0,0,0,0,1,1,0,0,1
Nanson,1,1,1,1,1,1,0,0,0,0,0,0,1,1,0,0,0
Baldwin,1,1,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0
Tideman alternative,1,1,1,1,1,1,1,0,1,0,0,0,0,1,0,0,0
Minimax,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0
Copeland,1,1,1,1,1,1,1,0,0,1,0,0,1,1,0,0,0
Black,1,1,0,1,1,0,0,0,0,1,0,0,1,1,0,0,0
Kemeny,1,1,1,1,1,1,1,1,0,1,0,0,1,1,0,0,0
Ranked pairs,1,1,1,1,1,1,1,1,1,1,0,0,1,1,0,0,0
Schulze,1,1,1,1,1,1,1,0,1,1,0,0,1,1,0,0,0
Borda,0,1,0,0,1,0,0,0,0,1,1,1,1,1,0,1,0
Bucklin,1,1,1,0,0,0,0,0,0,1,0,0,0,1,0,1,0
Approval,1,0,0,0,0,0,1,1,1,1,1,1,1,1,0,1,1
Majority Judgement,0,0,0,0,0,0,1,1,1,1,0,0,1,1,0,1,1
Score,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,1,1
STAR,0,1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0
Quadratic,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,0
Random ballot[Tn 7],0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1
Sortition[Tn 8],0,0,0,0,0,0,1,1,0,1,1,1,1,1,1,1,1

In [71]:
frequent = apriori(df.drop(['Ballot type'], axis=1), min_support=0.3, use_colnames=True)
rules = association_rules(frequent, metric='confidence', min_threshold=0.6)
maxfp = fpmax(df.drop(['Ballot type'], axis=1), min_support=0.3, use_colnames=True)

/home/danny/cuboulder/school/2026-spring-semester/CSCI4022/project/random_analysis/.venv/lib/python3.14/site-packages/mlxtend/frequent_patterns/fpcommon.py:175: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(
/home/danny/cuboulder/school/2026-spring-semester/CSCI4022/project/random_analysis/.venv/lib/python3.14/site-packages/mlxtend/frequent_patterns/association_rules.py:186: RuntimeWarning: invalid value encountered in divide
  cert_metric = np.where(certainty_denom == 0, 0, certainty_num / certainty_denom)
/home/danny/cuboulder/school/2026-spring-semester/CSCI4022/project/random_analysis/.venv/lib/python3.14/site-packages/mlxtend/frequent_patterns/fpcommon.py:175: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [73]:
for items in maxfp['itemsets']:
    display(items)

frozenset({'Homo\xadgeneity',
           'IIA/LIIA',
           'Mono\xadtone',
           'Reversal symmetry',
           'Smith-IIA'})

frozenset({'Condorcet loser',
           'Condorcet winner',
           'Homo\xadgeneity',
           'Majority loser',
           'Majority winner',
           'Mutual majority',
           'Smith'})

frozenset({'Homo\xadgeneity', 'No favorite betrayal'})

frozenset({'Clone\xadproof', 'Homo\xadgeneity', 'Smith-IIA'})

frozenset({'Consistency',
           'Homo\xadgeneity',
           'Later-no-help',
           'Mono\xadtone',
           'Partici\xadpation'})

frozenset({'Homo\xadgeneity',
           'Later-no-help',
           'Mono\xadtone',
           'Reversal symmetry'})

frozenset({'Condorcet loser',
           'Homo\xadgeneity',
           'Majority loser',
           'Mono\xadtone'})

frozenset({'Condorcet loser',
           'Homo\xadgeneity',
           'Majority loser',
           'Majority winner',
           'Reversal symmetry'})

frozenset({'Homo\xadgeneity', 'Majority winner', 'Mono\xadtone'})

In [78]:
pd.set_option('display.max_colwidth', 1000)
print(maxfp['itemsets'])

0                                             frozenset({Homo­geneity, Smith-IIA, Reversal symmetry, IIA/LIIA, Mono­tone})
1    frozenset({Majority winner, Mutual majority, Condorcet loser, Smith, Homo­geneity, Majority loser, Condorcet winner})
2                                                                          frozenset({Homo­geneity, No favorite betrayal})
3                                                                        frozenset({Homo­geneity, Clone­proof, Smith-IIA})
4                                         frozenset({Consistency, Homo­geneity, Mono­tone, Partici­pation, Later-no-help})
5                                                   frozenset({Homo­geneity, Later-no-help, Mono­tone, Reversal symmetry})
6                                                    frozenset({Homo­geneity, Condorcet loser, Majority loser, Mono­tone})
7                           frozenset({Majority winner, Condorcet loser, Homo­geneity, Majority loser, Reversal symmetry})
8                                                                    frozenset({Homo­geneity, Majority winner, Mono­tone})
Name: itemsets, dtype: object

In [ ]:
print(f"Found {len(rules)} association rules")
print("\nTop 30 rules by lift:")
display(rules.nlargest(30, 'lift')[['antecedents', 'consequents', 'support', 'confidence', 'lift']])

Found 2020 association rules

Top 30 rules by lift:

,antecedents,consequents,support,confidence,lift
228,"frozenset({Mutual majority, Condorcet winner})",frozenset({Smith}),0.304348,1.0,3.285714
231,frozenset({Smith}),"frozenset({Mutual majority, Condorcet winner})",0.304348,1.0,3.285714
516,"frozenset({Majority winner, Mutual majority, C...",frozenset({Smith}),0.304348,1.0,3.285714
520,"frozenset({Majority winner, Smith})","frozenset({Mutual majority, Condorcet winner})",0.304348,1.0,3.285714
523,"frozenset({Mutual majority, Condorcet winner})","frozenset({Majority winner, Smith})",0.304348,1.0,3.285714
526,frozenset({Smith}),"frozenset({Majority winner, Mutual majority, C...",0.304348,1.0,3.285714
639,"frozenset({Mutual majority, Majority loser, Co...",frozenset({Smith}),0.304348,1.0,3.285714
644,"frozenset({Mutual majority, Condorcet winner})","frozenset({Majority loser, Smith})",0.304348,1.0,3.285714
645,"frozenset({Majority loser, Smith})","frozenset({Mutual majority, Condorcet winner})",0.304348,1.0,3.285714
649,frozenset({Smith}),"frozenset({Mutual majority, Majority loser, Co...",0.304348,1.0,3.285714
756,"frozenset({Mutual majority, Condorcet loser, C...",frozenset({Smith}),0.304348,1.0,3.285714
761,"frozenset({Mutual majority, Condorcet winner})","frozenset({Condorcet loser, Smith})",0.304348,1.0,3.285714
762,"frozenset({Condorcet loser, Smith})","frozenset({Mutual majority, Condorcet winner})",0.304348,1.0,3.285714
766,frozenset({Smith}),"frozenset({Mutual majority, Condorcet loser, C...",0.304348,1.0,3.285714
780,"frozenset({Homo­geneity, Mutual majority, Cond...",frozenset({Smith}),0.304348,1.0,3.285714
784,"frozenset({Homo­geneity, Smith})","frozenset({Mutual majority, Condorcet winner})",0.304348,1.0,3.285714
787,"frozenset({Mutual majority, Condorcet winner})","frozenset({Homo­geneity, Smith})",0.304348,1.0,3.285714
790,frozenset({Smith}),"frozenset({Homo­geneity, Mutual majority, Cond...",0.304348,1.0,3.285714
958,"frozenset({Majority winner, Mutual majority, M...",frozenset({Smith}),0.304348,1.0,3.285714
963,"frozenset({Majority winner, Mutual majority, C...","frozenset({Majority loser, Smith})",0.304348,1.0,3.285714
964,"frozenset({Majority winner, Majority loser, Sm...","frozenset({Mutual majority, Condorcet winner})",0.304348,1.0,3.285714
969,"frozenset({Mutual majority, Majority loser, Co...","frozenset({Majority winner, Smith})",0.304348,1.0,3.285714
972,"frozenset({Majority winner, Smith})","frozenset({Mutual majority, Majority loser, Co...",0.304348,1.0,3.285714
976,"frozenset({Mutual majority, Condorcet winner})","frozenset({Majority winner, Majority loser, Sm...",0.304348,1.0,3.285714
977,"frozenset({Majority loser, Smith})","frozenset({Majority winner, Mutual majority, C...",0.304348,1.0,3.285714
981,frozenset({Smith}),"frozenset({Majority winner, Mutual majority, M...",0.304348,1.0,3.285714
1199,"frozenset({Majority winner, Mutual majority, C...",frozenset({Smith}),0.304348,1.0,3.285714
1205,"frozenset({Majority winner, Mutual majority, C...","frozenset({Condorcet loser, Smith})",0.304348,1.0,3.285714
1206,"frozenset({Majority winner, Condorcet loser, S...","frozenset({Mutual majority, Condorcet winner})",0.304348,1.0,3.285714
1210,"frozenset({Mutual majority, Condorcet loser, C...","frozenset({Majority winner, Smith})",0.304348,1.0,3.285714

In [ ]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({Majority winner}),frozenset({Majority loser}),0.652174,0.652174,0.521739,0.800000,1.226667,1.0,0.096408,1.739130,0.531250,0.666667,0.425000,0.800000
1,frozenset({Majority loser}),frozenset({Majority winner}),0.652174,0.652174,0.521739,0.800000,1.226667,1.0,0.096408,1.739130,0.531250,0.666667,0.425000,0.800000
2,frozenset({Majority winner}),frozenset({Mutual majority}),0.652174,0.434783,0.434783,0.666667,1.533333,1.0,0.151229,1.695652,1.000000,0.666667,0.410256,0.833333
3,frozenset({Mutual majority}),frozenset({Majority winner}),0.434783,0.652174,0.434783,1.000000,1.533333,1.0,0.151229,inf,0.615385,0.666667,1.000000,0.833333
4,frozenset({Majority winner}),frozenset({Condorcet winner}),0.652174,0.391304,0.391304,0.600000,1.533333,1.0,0.136106,1.521739,1.000000,0.600000,0.342857,0.800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015,"frozenset({Homo­geneity, Condorcet winner})","frozenset({Majority winner, Mutual majority, C...",0.391304,0.304348,0.304348,0.777778,2.555556,1.0,0.185255,3.130435,1.000000,0.777778,0.680556,0.888889
2016,"frozenset({Majority loser, Condorcet winner})","frozenset({Majority winner, Mutual majority, C...",0.347826,0.304348,0.304348,0.875000,2.875000,1.0,0.198488,5.565217,1.000000,0.875000,0.820313,0.937500
2017,frozenset({Mutual majority}),"frozenset({Majority winner, Condorcet loser, S...",0.434783,0.304348,0.304348,0.700000,2.300000,1.0,0.172023,2.318841,1.000000,0.700000,0.568750,0.850000
2018,frozenset({Smith}),"frozenset({Majority winner, Mutual majority, C...",0.304348,0.304348,0.304348,1.000000,3.285714,1.0,0.211720,inf,1.000000,1.000000,1.000000,1.000000
2019,frozenset({Condorcet winner}),"frozenset({Majority winner, Mutual majority, C...",0.391304,0.304348,0.304348,0.777778,2.555556,1.0,0.185255,3.130435,1.000000,0.777778,0.680556,0.888889